//Problem 29: How many distinct terms are 
//in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
import java.math.BigInteger;
import java.util.*;

class DistinctPowers {
	public static void main(String[] args) {
		HashSet<BigInteger> set = new HashSet<>();
		for (int a = 2; a <= 100; a++) {
			for (int b = 2; b <= 100; b++) {
				BigInteger result = BigInteger.valueOf(a).pow(b);
				set.add(result);
			}
		}
		System.out.println(set.size());
	}
}