//Problem: The sequence of triangle numbers is generated by adding the natural numbers. 
//So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
//What is the value of the first triangle number to have over five hundred divisors?

class Triangle500Divisors {
	public static void main(String[] args) {
		long n = 1;
		long i = 1;
		while (true) {
			n = (i*(i+1))/2;
			//count factors
			int factorCount = 0;
			for (int j = 1; j <= (long)Math.sqrt(n); j++) {
				if (n % j == 0) {
					factorCount++;
					long otherFactor = n / j;
					if (j != otherFactor)
						factorCount++;
				}
			}
			if (factorCount > 500)
				break;
			i++;
		}
		System.out.println(n);
	}
}
